### ISSUE TITLE
Compilation fails (freetype2 not found)

### ISSUE THREAD

**Issue by Skeletorjus** [srwareham/docker-ffmpeg-compiler#1]
The compilation fails after giving the following error:
`ERROR: freetype2 not found using pkg-config`

**Comment by srwareham** [comment]
Thanks for pointing this out. That was surprisingly tricky to track down. Actually surprised that's the only thing that's broken in two years.

**Comment by Skeletorjus** [comment]
Perfect! Thank you for the fast fix for this genuinely useful project!
