### ISSUE TITLE
silent fail

### ISSUE THREAD

**Issue by rienafairefr** [srwareham/docker-ffmpeg-compiler#3]
It seems to me the compilation steps ought to be linked by `&&`, not `;`, I faced a failed compile because the step `hg clone https://bitbucket.org/multicoreware/x265` failed for some reason. 
(probably this https://stackoverflow.com/questions/26952911/handshake-failure-when-trying-to-push-repository-to-bitbucket)
The rest of the steps continued without indication of failure, and the final ffmpeg compile couldn't ever hope to successfully work.

**Comment by srwareham** [comment]
Thanks, definitely agree. Unfortunately, my initial test of compiling this (as well as the original) failed. I don't really have the time to get to this right now, but certainly would welcome any PRs.
