### ISSUE TITLE
Upgrade to ubuntu:16.04, fix build errors

### ISSUE THREAD

**Issue by jamshid** [srwareham/docker-ffmpeg-compiler#4]
Not sure if it's broken for everyone but I encountered a lot build errors, e.g. `hg clone` SSL errors. Seemed easier to upgrade ubuntu, here is a working Dockerfile patch.
 
I don't know hot to test libopus (mentioned in readme), mp4 seems fine.

**Comment by srwareham** [comment]
Thanks! I'll try to look at this soon and merge in.

**Comment by srwareham** [comment]
All built and tested well, thanks for the contribution!
