### ISSUE TITLE
Bitbucket no longer supports Mercurial repositories

### ISSUE THREAD

**Issue by reedog117** [srwareham/docker-ffmpeg-compiler#8]
Script fails when attempting to `hg clone https://bitbucket.org/multicoreware/x265` - Mercurial repositories no longer supported by Bitbucket.

**Comment by srwareham** [comment]
Thanks! I'm currently traveling but will look into it when I have a computer handy. Also happy to accept a PR.

**Comment by srwareham** [comment]
Fixed, thanks!
